package main_test

import (
	"encoding/base64"
	"github.com/stretchr/testify/assert"
	"io"
	"strings"
	"testing"
)

func TestJson(t *testing.T) {
	reader := base64.NewDecoder(base64.StdEncoding, strings.NewReader(`eyJzdWJqZWN0IjoidGlkYl92X3VzZXItdmFsdWUiLCJ2ZXJzaW9uIjoxLCJpZCI6MSwic2NoZW1hIjoie1widHlwZVwiOlwicmVjb3JkXCIsXCJuYW1lXCI6XCJ1c2VyXCIsXCJuYW1lc3BhY2VcIjpcImRlZmF1bHQudlwiLFwiZmllbGRzXCI6W3tcIm5hbWVcIjpcImJpel9pZFwiLFwidHlwZVwiOntcInR5cGVcIjpcImxvbmdcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiQklHSU5UIFVOU0lHTkVEXCJ9fX0se1wibmFtZVwiOlwidXNlcl9pZFwiLFwidHlwZVwiOntcInR5cGVcIjpcImxvbmdcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiQklHSU5UIFVOU0lHTkVEXCJ9fX0se1wibmFtZVwiOlwidXNlcl9uYW1lXCIsXCJ0eXBlXCI6e1widHlwZVwiOlwic3RyaW5nXCIsXCJjb25uZWN0LnBhcmFtZXRlcnNcIjp7XCJ0aWRiX3R5cGVcIjpcIlRFWFRcIn19fSx7XCJkZWZhdWx0XCI6XCJcIixcIm5hbWVcIjpcImF2YXRhclwiLFwidHlwZVwiOntcInR5cGVcIjpcInN0cmluZ1wiLFwiY29ubmVjdC5wYXJhbWV0ZXJzXCI6e1widGlkYl90eXBlXCI6XCJURVhUXCJ9fX0se1wiZGVmYXVsdFwiOlwiXCIsXCJuYW1lXCI6XCJkZXNjcmlwdGlvblwiLFwidHlwZVwiOntcInR5cGVcIjpcInN0cmluZ1wiLFwiY29ubmVjdC5wYXJhbWV0ZXJzXCI6e1widGlkYl90eXBlXCI6XCJURVhUXCJ9fX0se1wiZGVmYXVsdFwiOjAsXCJuYW1lXCI6XCJnZW5kZXJcIixcInR5cGVcIjp7XCJ0eXBlXCI6XCJpbnRcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiSU5UXCJ9fX0se1wiZGVmYXVsdFwiOlwiXCIsXCJuYW1lXCI6XCJwaG9uZV9udW1iZXJcIixcInR5cGVcIjp7XCJ0eXBlXCI6XCJzdHJpbmdcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiVEVYVFwifX19LHtcImRlZmF1bHRcIjpcIkNVUlJFTlRfVElNRVNUQU1QXCIsXCJuYW1lXCI6XCJjdGltZVwiLFwidHlwZVwiOntcInR5cGVcIjpcInN0cmluZ1wiLFwiY29ubmVjdC5wYXJhbWV0ZXJzXCI6e1widGlkYl90eXBlXCI6XCJUSU1FU1RBTVBcIn19fSx7XCJkZWZhdWx0XCI6XCJDVVJSRU5UX1RJTUVTVEFNUFwiLFwibmFtZVwiOlwibXRpbWVcIixcInR5cGVcIjp7XCJ0eXBlXCI6XCJzdHJpbmdcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiVElNRVNUQU1QXCJ9fX0se1wiZGVmYXVsdFwiOlwiQ1VSUkVOVF9USU1FU1RBTVBcIixcIm5hbWVcIjpcImJ0aW1lXCIsXCJ0eXBlXCI6e1widHlwZVwiOlwic3RyaW5nXCIsXCJjb25uZWN0LnBhcmFtZXRlcnNcIjp7XCJ0aWRiX3R5cGVcIjpcIlRJTUVTVEFNUFwifX19XX0ifQ==`))
	bytes, err := io.ReadAll(reader)
	assert.Nil(t, err)
	t.Log(string(bytes))
}
