package main_test

import (
	"testing"
)

func TestJson(t *testing.T) {
	//reader := base64.NewDecoder(base64.StdEncoding, strings.NewReader(`eyJzdWJqZWN0IjoidGlkYl92X3VzZXItdmFsdWUiLCJ2ZXJzaW9uIjoxLCJpZCI6MSwic2NoZW1hIjoie1widHlwZVwiOlwicmVjb3JkXCIsXCJuYW1lXCI6XCJ1c2VyXCIsXCJuYW1lc3BhY2VcIjpcImRlZmF1bHQudlwiLFwiZmllbGRzXCI6W3tcIm5hbWVcIjpcImJpel9pZFwiLFwidHlwZVwiOntcInR5cGVcIjpcImxvbmdcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiQklHSU5UIFVOU0lHTkVEXCJ9fX0se1wibmFtZVwiOlwidXNlcl9pZFwiLFwidHlwZVwiOntcInR5cGVcIjpcImxvbmdcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiQklHSU5UIFVOU0lHTkVEXCJ9fX0se1wibmFtZVwiOlwidXNlcl9uYW1lXCIsXCJ0eXBlXCI6e1widHlwZVwiOlwic3RyaW5nXCIsXCJjb25uZWN0LnBhcmFtZXRlcnNcIjp7XCJ0aWRiX3R5cGVcIjpcIlRFWFRcIn19fSx7XCJkZWZhdWx0XCI6XCJcIixcIm5hbWVcIjpcImF2YXRhclwiLFwidHlwZVwiOntcInR5cGVcIjpcInN0cmluZ1wiLFwiY29ubmVjdC5wYXJhbWV0ZXJzXCI6e1widGlkYl90eXBlXCI6XCJURVhUXCJ9fX0se1wiZGVmYXVsdFwiOlwiXCIsXCJuYW1lXCI6XCJkZXNjcmlwdGlvblwiLFwidHlwZVwiOntcInR5cGVcIjpcInN0cmluZ1wiLFwiY29ubmVjdC5wYXJhbWV0ZXJzXCI6e1widGlkYl90eXBlXCI6XCJURVhUXCJ9fX0se1wiZGVmYXVsdFwiOjAsXCJuYW1lXCI6XCJnZW5kZXJcIixcInR5cGVcIjp7XCJ0eXBlXCI6XCJpbnRcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiSU5UXCJ9fX0se1wiZGVmYXVsdFwiOlwiXCIsXCJuYW1lXCI6XCJwaG9uZV9udW1iZXJcIixcInR5cGVcIjp7XCJ0eXBlXCI6XCJzdHJpbmdcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiVEVYVFwifX19LHtcImRlZmF1bHRcIjpcIkNVUlJFTlRfVElNRVNUQU1QXCIsXCJuYW1lXCI6XCJjdGltZVwiLFwidHlwZVwiOntcInR5cGVcIjpcInN0cmluZ1wiLFwiY29ubmVjdC5wYXJhbWV0ZXJzXCI6e1widGlkYl90eXBlXCI6XCJUSU1FU1RBTVBcIn19fSx7XCJkZWZhdWx0XCI6XCJDVVJSRU5UX1RJTUVTVEFNUFwiLFwibmFtZVwiOlwibXRpbWVcIixcInR5cGVcIjp7XCJ0eXBlXCI6XCJzdHJpbmdcIixcImNvbm5lY3QucGFyYW1ldGVyc1wiOntcInRpZGJfdHlwZVwiOlwiVElNRVNUQU1QXCJ9fX0se1wiZGVmYXVsdFwiOlwiQ1VSUkVOVF9USU1FU1RBTVBcIixcIm5hbWVcIjpcImJ0aW1lXCIsXCJ0eXBlXCI6e1widHlwZVwiOlwic3RyaW5nXCIsXCJjb25uZWN0LnBhcmFtZXRlcnNcIjp7XCJ0aWRiX3R5cGVcIjpcIlRJTUVTVEFNUFwifX19XX0ifQ==`))
	//bytes, err := io.ReadAll(reader)
	//assert.Nil(t, err)
	//t.Log(string(bytes))
	a := "curl -X '' -d '{\"schema\":\"{\\\"type\\\":\\\"record\\\",\\\"name\\\":\\\"user\\\",\\\"namespace\\\":\\\"default.v\\\",\\\"fields\\\":[{\\\"name\\\":\\\"biz_id\\\",\\\"type\\\":{\\\"type\\\":\\\"long\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"BIGINT UNSIGNED\\\"}}},{\\\"name\\\":\\\"user_id\\\",\\\"type\\\":{\\\"type\\\":\\\"long\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"BIGINT UNSIGNED\\\"}}},{\\\"name\\\":\\\"user_name\\\",\\\"type\\\":{\\\"type\\\":\\\"string\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"TEXT\\\"}}},{\\\"default\\\":\\\"\\\",\\\"name\\\":\\\"avatar\\\",\\\"type\\\":{\\\"type\\\":\\\"string\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"TEXT\\\"}}},{\\\"default\\\":\\\"\\\",\\\"name\\\":\\\"description\\\",\\\"type\\\":{\\\"type\\\":\\\"string\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"TEXT\\\"}}},{\\\"default\\\":0,\\\"name\\\":\\\"gender\\\",\\\"type\\\":{\\\"type\\\":\\\"int\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"INT\\\"}}},{\\\"default\\\":\\\"\\\",\\\"name\\\":\\\"phone_number\\\",\\\"type\\\":{\\\"type\\\":\\\"string\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"TEXT\\\"}}},{\\\"default\\\":\\\"CURRENT_TIMESTAMP\\\",\\\"name\\\":\\\"ctime\\\",\\\"type\\\":{\\\"type\\\":\\\"string\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"TIMESTAMP\\\"}}},{\\\"default\\\":\\\"CURRENT_TIMESTAMP\\\",\\\"name\\\":\\\"mtime\\\",\\\"type\\\":{\\\"type\\\":\\\"string\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"TIMESTAMP\\\"}}},{\\\"default\\\":\\\"CURRENT_TIMESTAMP\\\",\\\"name\\\":\\\"btime\\\",\\\"type\\\":{\\\"type\\\":\\\"string\\\",\\\"connect.parameters\\\":{\\\"tidb_type\\\":\\\"TIMESTAMP\\\"}}}]}\"}' -H 'Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2' -H 'Accept-Encoding: gzip, deflate, br' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Content-Length: 1311' -H 'Content-Type: application/vnd.schemaregistry.v1+json' -H 'Postman-Token: f78fbf9d-e297-451f-ad56-fb3ea202ec4f' -H 'Pragma: no-cache' -H 'User-Agent: Java/11.0.14.1' 'http://redpanda-cluster-0.redpanda-cluster.redpanda-cluster-default.svc.cluster.local:8081/subjects/tidb_v_user-value?normalize=false&deleted=true'"
	t.Log(a)
}
